version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: booking_postgres
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
